name: analisis-peliculas
services:
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:4.1.0-management
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - local_net
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 10s
            timeout: 10s
            retries: 10
        volumes:
            - /Users/melinajauregui/Documents/distro-tps/tp-grupal/rabbitmq/rabbitmq.conf:/etc/rabbitmq/conf.d/rabbitmq.conf

    sentiment_server0:
        container_name: sentiment_server0
        build:
            context: .
            dockerfile: nlp/python_server/Dockerfile
        networks:
            - local_net
        environment:
            - GRPC_PORT=50050
            - GRPC_WORKERS=30
            - NAME=sentiment_server0
            - MONITOR_ADDRESSES=monitor0:9000,monitor1:9001,monitor2:9002
        healthcheck:
            test: ['CMD', 'sh', '-c', 'nc -z localhost 50050']
            interval: 10s
            timeout: 10s
            retries: 10

    sentiment_server1:
        container_name: sentiment_server1
        build:
            context: .
            dockerfile: nlp/python_server/Dockerfile
        networks:
            - local_net
        environment:
            - GRPC_PORT=50051
            - GRPC_WORKERS=30
            - NAME=sentiment_server1
            - MONITOR_ADDRESSES=monitor0:9000,monitor1:9001,monitor2:9002
        healthcheck:
            test: ['CMD', 'sh', '-c', 'nc -z localhost 50051']
            interval: 10s
            timeout: 10s
            retries: 10

    coordinator:
        container_name: coordinator
        build:
            context: .
            dockerfile: coordinator/Dockerfile
        entrypoint: /coordinator
        networks:
            - local_net
        environment:
            - N_WORKERS=2
            - N_RATINGS_CONSUMERS=10
            - PREFETCH=1 # Potential optimization
            - NAME=coordinator
            - MONITOR_ADDRESSES=monitor0:9000,monitor1:9001,monitor2:9002
        depends_on:
            rabbitmq:
                condition: service_healthy

    worker0:
        container_name: worker0
        build:
            context: .
            dockerfile: worker/Dockerfile
        entrypoint: /worker
        environment: 
            - WORKER_ID=0
            - N_WORKERS=2
            - N_REDUCERS_BY_COUNTRY_SUM_BUDGETS=3
            - SERVER_PORT=1234
            - PREFETCH=1 # Potential optimization
            - NAME=worker0
            - MONITOR_ADDRESSES=monitor0:9000,monitor1:9001,monitor2:9002
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy

    worker1:
        container_name: worker1
        build:
            context: .
            dockerfile: worker/Dockerfile
        entrypoint: /worker
        environment: 
            - WORKER_ID=1
            - N_WORKERS=2
            - N_REDUCERS_BY_COUNTRY_SUM_BUDGETS=3
            - SERVER_PORT=1234
            - PREFETCH=1 # Potential optimization
            - NAME=worker1
            - MONITOR_ADDRESSES=monitor0:9000,monitor1:9001,monitor2:9002
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy

    reduce_by_country_sum_budget0:
        container_name: reduce_by_country_sum_budget0
        build:
            context: .
            dockerfile: map_reducer/main/reduce_by_country_sum_budget/Dockerfile
        entrypoint: /map_reducer
        environment:
            - WORKER_ID=0
            - WORKER_COUNT=3
            - WORKER_OUTPUT_COUNT=2
            - NAME=reduce_by_country_sum_budget0
            - MONITOR_ADDRESSES=monitor0:9000,monitor1:9001,monitor2:9002
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy

    reduce_by_country_sum_budget1:
        container_name: reduce_by_country_sum_budget1
        build:
            context: .
            dockerfile: map_reducer/main/reduce_by_country_sum_budget/Dockerfile
        entrypoint: /map_reducer
        environment:
            - WORKER_ID=1
            - WORKER_COUNT=3
            - WORKER_OUTPUT_COUNT=2
            - NAME=reduce_by_country_sum_budget1
            - MONITOR_ADDRESSES=monitor0:9000,monitor1:9001,monitor2:9002
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy

    reduce_by_country_sum_budget2:
        container_name: reduce_by_country_sum_budget2
        build:
            context: .
            dockerfile: map_reducer/main/reduce_by_country_sum_budget/Dockerfile
        entrypoint: /map_reducer
        environment:
            - WORKER_ID=2
            - WORKER_COUNT=3
            - WORKER_OUTPUT_COUNT=2
            - NAME=reduce_by_country_sum_budget2
            - MONITOR_ADDRESSES=monitor0:9000,monitor1:9001,monitor2:9002
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy

    reduce_top_5_by_budget0:
        container_name: reduce_top_5_by_budget0
        build:
            context: .
            dockerfile: map_reducer/main/reduce_top_5_by_budget/Dockerfile
        entrypoint: /map_reducer
        environment:
            - WORKER_ID=0
            - WORKER_COUNT=2
            - WORKER_OUTPUT_COUNT=1
            - NAME=reduce_top_5_by_budget0
            - MONITOR_ADDRESSES=monitor0:9000,monitor1:9001,monitor2:9002
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy

    reduce_top_5_by_budget1:
        container_name: reduce_top_5_by_budget1
        build:
            context: .
            dockerfile: map_reducer/main/reduce_top_5_by_budget/Dockerfile
        entrypoint: /map_reducer
        environment:
            - WORKER_ID=1
            - WORKER_COUNT=2
            - WORKER_OUTPUT_COUNT=1
            - NAME=reduce_top_5_by_budget1
            - MONITOR_ADDRESSES=monitor0:9000,monitor1:9001,monitor2:9002
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy

    client0:
        container_name: client0
        build:
            context: .
            dockerfile: client/Dockerfile
        entrypoint: /client
        environment:
            - SERVER_PORT=endpoint:9876
            - NAME=client0
            - MONITOR_ADDRESSES=monitor0:9000,monitor1:9001,monitor2:9002
        networks:
            - local_net
        depends_on:
            - endpoint
        volumes:
            - /Users/melinajauregui/Documents/distro-tps/tp-grupal/client/datasets:/datasets

    endpoint:
        container_name: endpoint
        build:
            context: .
            dockerfile: endpoint/Dockerfile
        entrypoint: /endpoint
        environment:
            - ENDPOINT_PORT=9876
            - NAME=endpoint
            - MONITOR_ADDRESSES=monitor0:9000,monitor1:9001,monitor2:9002
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy

networks:
    local_net:
        name: local_net
        ipam:
            driver: default
            config:
                - subnet: 172.25.125.0/24

