name: analisis-peliculas
services:
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:4.0.8-management
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - local_net
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 10s
            timeout: 10s
            retries: 10

    coordinator:
        container_name: coordinator
        build:
            context: .
            dockerfile: coordinator/Dockerfile
        entrypoint: /coordinator
        networks:
            - local_net
        environment:
            - NUMBER_OF_FILTERS=1
            - NUMBER_OF_REDUCE_BY_COUNTRY_SUM_BUDGETS=1
            - NUMBER_OF_REDUCE_TOP_5_BY_BUDGETS=1
        depends_on:
            rabbitmq:
                condition: service_healthy
        volumes:
            - /Users/melinajauregui/Documents/distro-tps/tp-grupal/coordinator/datasets:/datasets

    filter1:
        container_name: filter1
        build:
            context: .
            dockerfile: worker/Dockerfile
        entrypoint: /worker
        environment:
            - WORKER_ID=1
            - SERVER_PORT=1234
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy

    reduce_by_country_sum_budget1:
        container_name: reduce_by_country_sum_budget1
        build:
            context: .
            dockerfile: map_reducer/main/reduce_by_country_sum_budget/Dockerfile
        entrypoint: /map_reducer
        environment:
            - WORKER_ID=1
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy

    reduce_top_5_by_budget1:
        container_name: reduce_top_5_by_budget1
        build:
            context: .
            dockerfile: map_reducer/main/reduce_top_5_by_budget/Dockerfile
        entrypoint: /map_reducer
        environment:
            - WORKER_ID=1
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy

    client:
        container_name: client
        build:
            context: .
            dockerfile: client/Dockerfile
        entrypoint: /client
        environment:
            - SERVER_PORT=endpoint:9876
        networks:
            - local_net
        depends_on:
            - endpoint
        volumes:
            - /Users/melinajauregui/Documents/distro-tps/tp-grupal/client/datasets:/datasets

    endpoint:
        container_name: endpoint
        build:
            context: .
            dockerfile: endpoint/Dockerfile
        entrypoint: /endpoint
        environment:
            - ENDPOINT_PORT=9876
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy

networks:
    local_net:
        name: local_net
        ipam:
            driver: default
            config:
                - subnet: 172.25.125.0/24

