name: analisis-peliculas
services:
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:4.1.0-management
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - local_net
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 10s
            timeout: 10s
            retries: 10
        volumes:
            - /Users/melinajauregui/Documents/distro-tps/tp-grupal/rabbitmq/rabbitmq.conf:/etc/rabbitmq/conf.d/rabbitmq.conf

    sentiment_server:
        container_name: sentiment_server
        build:
            context: .
            dockerfile: worker/nlp/python_server/Dockerfile
        ports:
            - "50051:50051"
        networks:
            - local_net
        environment:
            - GRPC_PORT=50051
            - GRPC_WORKERS=30
        healthcheck:
            test: ncat -zv localhost 50051
            interval: 10s
            timeout: 10s
            retries: 10

    coordinator:
        container_name: coordinator
        build:
            context: .
            dockerfile: coordinator/Dockerfile
        entrypoint: /coordinator
        networks:
            - local_net
        environment:
            - NUMBER_OF_WORKERS=5
            - NUMBER_OF_REDUCE_BY_COUNTRY_SUM_BUDGETS=1
            - NUMBER_OF_REDUCE_TOP_5_BY_BUDGETS=1
            - PREFETCH=1
        depends_on:
            rabbitmq:
                condition: service_healthy
            sentiment_server:
                condition: service_healthy

    worker1:
        container_name: worker1
        build:
            context: .
            dockerfile: worker/Dockerfile
        entrypoint: /worker
        environment: 
            - WORKER_ID=1
            - N_JOINERS_CREDITS=1
            - N_JOINERS_RATINGS=1
            - N_WORKERS=5
            - NLP_GRPC_ADDR=sentiment_server:50051
            - SERVER_PORT=1234
            - PREFETCH=1
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy
            sentiment_server:
                condition: service_healthy

    worker2:
        container_name: worker2
        build:
            context: .
            dockerfile: worker/Dockerfile
        entrypoint: /worker
        environment: 
            - WORKER_ID=2
            - N_JOINERS_CREDITS=1
            - N_JOINERS_RATINGS=1
            - N_WORKERS=5
            - NLP_GRPC_ADDR=sentiment_server:50051
            - SERVER_PORT=1234
            - PREFETCH=1
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy
            sentiment_server:
                condition: service_healthy

    worker3:
        container_name: worker3
        build:
            context: .
            dockerfile: worker/Dockerfile
        entrypoint: /worker
        environment: 
            - WORKER_ID=3
            - N_JOINERS_CREDITS=1
            - N_JOINERS_RATINGS=1
            - N_WORKERS=5
            - NLP_GRPC_ADDR=sentiment_server:50051
            - SERVER_PORT=1234
            - PREFETCH=1
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy
            sentiment_server:
                condition: service_healthy

    worker4:
        container_name: worker4
        build:
            context: .
            dockerfile: worker/Dockerfile
        entrypoint: /worker
        environment: 
            - WORKER_ID=4
            - N_JOINERS_CREDITS=1
            - N_JOINERS_RATINGS=1
            - N_WORKERS=5
            - NLP_GRPC_ADDR=sentiment_server:50051
            - SERVER_PORT=1234
            - PREFETCH=1
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy
            sentiment_server:
                condition: service_healthy

    worker5:
        container_name: worker5
        build:
            context: .
            dockerfile: worker/Dockerfile
        entrypoint: /worker
        environment: 
            - WORKER_ID=5
            - N_JOINERS_CREDITS=1
            - N_JOINERS_RATINGS=1
            - N_WORKERS=5
            - NLP_GRPC_ADDR=sentiment_server:50051
            - SERVER_PORT=1234
            - PREFETCH=1
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy
            sentiment_server:
                condition: service_healthy

    lean_worker1:
        container_name: lean_worker1
        build:
            context: .
            dockerfile: lean_worker/Dockerfile
        entrypoint: /lean_worker
        environment:
            - WORKER_ID=1
            - SERVER_PORT=1234
            - N_WORKERS=5
            - PREFETCH=1
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy
            sentiment_server:
                condition: service_healthy

    lean_worker2:
        container_name: lean_worker2
        build:
            context: .
            dockerfile: lean_worker/Dockerfile
        entrypoint: /lean_worker
        environment:
            - WORKER_ID=2
            - SERVER_PORT=1234
            - N_WORKERS=5
            - PREFETCH=1
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy
            sentiment_server:
                condition: service_healthy

    lean_worker3:
        container_name: lean_worker3
        build:
            context: .
            dockerfile: lean_worker/Dockerfile
        entrypoint: /lean_worker
        environment:
            - WORKER_ID=3
            - SERVER_PORT=1234
            - N_WORKERS=5
            - PREFETCH=1
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy
            sentiment_server:
                condition: service_healthy

    lean_worker4:
        container_name: lean_worker4
        build:
            context: .
            dockerfile: lean_worker/Dockerfile
        entrypoint: /lean_worker
        environment:
            - WORKER_ID=4
            - SERVER_PORT=1234
            - N_WORKERS=5
            - PREFETCH=1
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy
            sentiment_server:
                condition: service_healthy

    lean_worker5:
        container_name: lean_worker5
        build:
            context: .
            dockerfile: lean_worker/Dockerfile
        entrypoint: /lean_worker
        environment:
            - WORKER_ID=5
            - SERVER_PORT=1234
            - N_WORKERS=5
            - PREFETCH=1
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy
            sentiment_server:
                condition: service_healthy

    joiner_rating1:
        container_name: joiner_rating1
        build:
            context: .
            dockerfile: joiners/joiner_ratings_worker/Dockerfile
        entrypoint: /joiners
        environment:
            - WORKER_ID=1
            - SERVER_PORT=1234
            - WORKER_COUNT=
            - PREFETCH=1
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy
            sentiment_server:
                condition: service_healthy

    reduce_top_bottom_avg_rating1:
        container_name: reduce_top_bottom_avg_rating1
        build:
            context: .
            dockerfile: map_reducer/main/reduce_top_bottom_avg_rating/Dockerfile
        entrypoint: /map_reducer
        environment:
            - WORKER_ID=1
            - WORKER_COUNT=1
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy

    reduce_by_movieid1:
        container_name: reduce_by_movieid1
        build:
            context: .
            dockerfile: map_reducer/main/reduce_by_movieId/Dockerfile
        entrypoint: /map_reducer
        environment:
            - WORKER_ID=1
            - WORKER_CONDI=1
            - WORKER_COUNT=10
            - PREFETCH=1
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy

    reduce_by_movieid2:
        container_name: reduce_by_movieid2
        build:
            context: .
            dockerfile: map_reducer/main/reduce_by_movieId/Dockerfile
        entrypoint: /map_reducer
        environment:
            - WORKER_ID=2
            - WORKER_CONDI=1
            - WORKER_COUNT=10
            - PREFETCH=1
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy

    reduce_by_movieid3:
        container_name: reduce_by_movieid3
        build:
            context: .
            dockerfile: map_reducer/main/reduce_by_movieId/Dockerfile
        entrypoint: /map_reducer
        environment:
            - WORKER_ID=3
            - WORKER_CONDI=1
            - WORKER_COUNT=10
            - PREFETCH=1
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy

    reduce_by_movieid4:
        container_name: reduce_by_movieid4
        build:
            context: .
            dockerfile: map_reducer/main/reduce_by_movieId/Dockerfile
        entrypoint: /map_reducer
        environment:
            - WORKER_ID=4
            - WORKER_CONDI=1
            - WORKER_COUNT=10
            - PREFETCH=1
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy

    reduce_by_movieid5:
        container_name: reduce_by_movieid5
        build:
            context: .
            dockerfile: map_reducer/main/reduce_by_movieId/Dockerfile
        entrypoint: /map_reducer
        environment:
            - WORKER_ID=5
            - WORKER_CONDI=1
            - WORKER_COUNT=10
            - PREFETCH=1
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy

    reduce_by_movieid6:
        container_name: reduce_by_movieid6
        build:
            context: .
            dockerfile: map_reducer/main/reduce_by_movieId/Dockerfile
        entrypoint: /map_reducer
        environment:
            - WORKER_ID=6
            - WORKER_CONDI=1
            - WORKER_COUNT=10
            - PREFETCH=1
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy

    reduce_by_movieid7:
        container_name: reduce_by_movieid7
        build:
            context: .
            dockerfile: map_reducer/main/reduce_by_movieId/Dockerfile
        entrypoint: /map_reducer
        environment:
            - WORKER_ID=7
            - WORKER_CONDI=1
            - WORKER_COUNT=10
            - PREFETCH=1
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy

    reduce_by_movieid8:
        container_name: reduce_by_movieid8
        build:
            context: .
            dockerfile: map_reducer/main/reduce_by_movieId/Dockerfile
        entrypoint: /map_reducer
        environment:
            - WORKER_ID=8
            - WORKER_CONDI=1
            - WORKER_COUNT=10
            - PREFETCH=1
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy

    reduce_by_movieid9:
        container_name: reduce_by_movieid9
        build:
            context: .
            dockerfile: map_reducer/main/reduce_by_movieId/Dockerfile
        entrypoint: /map_reducer
        environment:
            - WORKER_ID=9
            - WORKER_CONDI=1
            - WORKER_COUNT=10
            - PREFETCH=1
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy

    reduce_by_movieid10:
        container_name: reduce_by_movieid10
        build:
            context: .
            dockerfile: map_reducer/main/reduce_by_movieId/Dockerfile
        entrypoint: /map_reducer
        environment:
            - WORKER_ID=10
            - WORKER_CONDI=1
            - WORKER_COUNT=10
            - PREFETCH=1
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy

    client1:
        container_name: client1
        build:
            context: .
            dockerfile: client/Dockerfile
        entrypoint: /client
        environment:
            - SERVER_PORT=endpoint:9876
        networks:
            - local_net
        depends_on:
            - endpoint
        volumes:
            - /Users/melinajauregui/Documents/distro-tps/tp-grupal/client/datasets:/datasets

    client2:
        container_name: client2
        build:
            context: .
            dockerfile: client/Dockerfile
        entrypoint: /client
        environment:
            - SERVER_PORT=endpoint:9876
        networks:
            - local_net
        depends_on:
            - endpoint
        volumes:
            - /Users/melinajauregui/Documents/distro-tps/tp-grupal/client/datasets:/datasets

    endpoint:
        container_name: endpoint
        build:
            context: .
            dockerfile: endpoint/Dockerfile
        entrypoint: /endpoint
        environment:
            - ENDPOINT_PORT=9876
        networks:
            - local_net
        depends_on:
            rabbitmq:
                condition: service_healthy

networks:
    local_net:
        name: local_net
        ipam:
            driver: default
            config:
                - subnet: 172.25.125.0/24

