// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: sentiment.proto

package nlp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SentimentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SentimentRequest) Reset() {
	*x = SentimentRequest{}
	mi := &file_sentiment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SentimentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentimentRequest) ProtoMessage() {}

func (x *SentimentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentiment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentimentRequest.ProtoReflect.Descriptor instead.
func (*SentimentRequest) Descriptor() ([]byte, []int) {
	return file_sentiment_proto_rawDescGZIP(), []int{0}
}

func (x *SentimentRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SentimentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SentimentResponse) Reset() {
	*x = SentimentResponse{}
	mi := &file_sentiment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SentimentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentimentResponse) ProtoMessage() {}

func (x *SentimentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentiment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentimentResponse.ProtoReflect.Descriptor instead.
func (*SentimentResponse) Descriptor() ([]byte, []int) {
	return file_sentiment_proto_rawDescGZIP(), []int{1}
}

func (x *SentimentResponse) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SentimentResponse) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_sentiment_proto protoreflect.FileDescriptor

const file_sentiment_proto_rawDesc = "" +
	"\n" +
	"\x0fsentiment.proto\x12\tsentiment\"&\n" +
	"\x10SentimentRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"?\n" +
	"\x11SentimentResponse\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score2Y\n" +
	"\x11SentimentAnalyzer\x12D\n" +
	"\aAnalyze\x12\x1b.sentiment.SentimentRequest\x1a\x1c.sentiment.SentimentResponseB\x13Z\x11../go_client/;nlpb\x06proto3"

var (
	file_sentiment_proto_rawDescOnce sync.Once
	file_sentiment_proto_rawDescData []byte
)

func file_sentiment_proto_rawDescGZIP() []byte {
	file_sentiment_proto_rawDescOnce.Do(func() {
		file_sentiment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sentiment_proto_rawDesc), len(file_sentiment_proto_rawDesc)))
	})
	return file_sentiment_proto_rawDescData
}

var file_sentiment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sentiment_proto_goTypes = []any{
	(*SentimentRequest)(nil),  // 0: sentiment.SentimentRequest
	(*SentimentResponse)(nil), // 1: sentiment.SentimentResponse
}
var file_sentiment_proto_depIdxs = []int32{
	0, // 0: sentiment.SentimentAnalyzer.Analyze:input_type -> sentiment.SentimentRequest
	1, // 1: sentiment.SentimentAnalyzer.Analyze:output_type -> sentiment.SentimentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sentiment_proto_init() }
func file_sentiment_proto_init() {
	if File_sentiment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sentiment_proto_rawDesc), len(file_sentiment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sentiment_proto_goTypes,
		DependencyIndexes: file_sentiment_proto_depIdxs,
		MessageInfos:      file_sentiment_proto_msgTypes,
	}.Build()
	File_sentiment_proto = out.File
	file_sentiment_proto_goTypes = nil
	file_sentiment_proto_depIdxs = nil
}
